version: "3.9"
services:
  zfile:
    image: stilleshan/zfile
    container_name: zfile
    ports:
      - 8555:8080
    volumes:
      - ./conf:/root/.zfile-v4
      - ../Data/external:/root/zfile/figma
      - ../Data/next:/root/zfile/next
      # - ../Data/zfile/test:/root/zfile/data/test
      # - ../Data/zfile/figma:/root/zfile/data/figma
    restart: always
  proxy:
    image: nginx:latest
    container_name: nginx-zfile
    ports:
      - 8015:8015
      - 443:443
    volumes:
      - ./proxy/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/certs:/etc/nginx/certs
      - ./nginx-log:/etc/nginx/logs
      # - ##### original
      # - ./proxy/legacy/conf/nginx.conf:/etc/nginx/nginx.conf
      # - ./proxy/legacy/certs:/etc/nginx/certs
    depends_on:
      - zfile

